name: Yarn Works

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install With Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Check Build process
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: workspaces run build
